const songs = [
  {
    
     _id: "1",
    name: "7:00",
    artist: "Bryson Tiller",
    isPlaying: false,
    color: "#00308F",
    image: "./songs_images/700.png",
      src: "./songs/7.mp3",
  
  },
  {
    _id: "2",
    name: "Ladbroke Grove",
    artist: "AJ Tracey",
    isPlaying: false,
    color: "#C76BDB",
    image: "./songs_images/ladbroke.jpg",
    src: "./songs/Ladbroke-Grove.mp3",
  },
  {
    _id: "3",
    name: "Take Me To The Sun",
    artist: "d4vd",
    isPlaying: false,
    color: "#C76BDB",
    image: "./songs_images/sun.jpg",
    src: "./songs/Take-Me-To-The-Sun.mp3",
  },
  {
    _id: "4",
    name: "Into It",
    artist: "Chase Atlantic",
    isPlaying: false,
    color: "#C76BDB",
    image: "./songs_images/intoit.jpg",
    src: "./songs/Into-it.mp3",
  },
  {
    _id: "5",
    name: "Wednesday Night Interlude",
    artist: "Drake ft. PARTYNEXTDOOR",
    isPlaying: false,
    color:"#C76BDB",
    image: "./songs_images/wednesday.jpg ",
    src: "./songs/Wednesday-Night-Interlude.mp3",
  },
  {
    _id: "6",
    name: "Novacane",
    artist: "Frank Ocean",
    isPlaying: false,
    color:"#C76BDB",
    image: "./songs_images/novacane.jpg",
    src: "./songs/Novacane.mp3",
  },
  {
    _id: "7",
    name: "Jealous",
    artist: "Future, Metro Boomin",
    isPlaying: false,
    color:"#C76BDB",
    image: "./songs_images/jelous.jpg",
    src: "./songs/Jealous.mp3",
  },
  {
    _id: "8",
    name: "a m a r i",
    artist: "J. Cole",
    isPlaying: false,
    color:"#C76BDB",
    image: "./songs_images/amari.jpg",
    src: "./songs/amari.mp3",
  },
  {
    _id: "9",
    name: "Iris",
    artist: "Goo Goo Dolls",
    isPlaying: false,
    color:"#C76BDB",
    image:  "./songs_images/iris.jpg",
    src: "./songs/Iris.mp3",
  },
  {
    _id: "10",
    name: "Love Yourz",
    artist: "J. Cole",
    isPlaying: false,
    color:"#C76BDB",
    image: "./songs_images/love-yourz.jpg",
    src: "./songs/love-yourz.mp3",
  },
  {
    _id: "11",
    name: "Never Love Again",
    artist: "Eminem",
    isPlaying: false,
    color:"#C76BDB",
    image: "./songs_images/neverlove.jpg",
    src: "./songs/Never-love-again.mp3",
  },
  {
    _id: "12",
    name: "TELEKINESIS",
    artist: "Travis Scott ft. SZA, Future",
    isPlaying: false,
    color:"#C76BDB",
    image: "./songs_images/telekenesis.png",
    src: "./songs/TELEKINESIS.mp3",
  },
];
export default songs;
